[project]
name = "ane-drive-perc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.13.0",
    "pillow>=12.2.0",
    "ultralytics>=8.4.46",
]

[project.scripts]
ane-drive-perc = "ane_drive_perc:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[tool.basedpyright]
typeCheckingMode = "basic"
